name: Generate Snake Contribution

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
  generate:
    runs-on: ubuntu-latest
    steps:
      # WAJIB: checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate snake & auto push ke branch output
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: mihsnfaa
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
